language: python
sudo: required
python: 3.6

env:
  - DJANGO_SETTINGS_MODULE=example.settings.test

install:
  - pip3 install -r requirements-dev.txt

script:
  - py.test

branches:
  only:
    - master
